language: node_js
node_js:
  - 4.1
install:
  - npm install -g grunt-cli
  - npm install grunt
  # - npm install grunt-contrib-copy
  - npm install grunt-contrib-nodeunit
  # - npm install grunt-contrib-clean
  # - npm install grunt-contrib-uglify
  # - npm install grunt-contrib-jshint
  # - npm install grunt-contrib-concat
  # - npm install grunt-contrib-cssmin
  # - npm install grunt-contrib-less
  # - npm install grunt-react
  # - npm install grunt-replace

  - npm install jsdom
  - npm install jquery
  - npm install jsface
  - npm install moment
  - npm install jquery-deparam
  - npm install jquery-mousewheel
  - npm install react
  - npm install react-dom
  - npm install bootstrap-fileinput-npm
  - npm install bootstrap

#after_success:
#  - git config --global user.email "bradwoo8621@gmail.com"
#  - git config --global user.name "bradwoo8621"
#  - npm version patch

#notifications:
#  slack: nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ

notifications:
  slack:
    rooms:
      - nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ#travis-ci
#      - nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ#random

deploy:
    provider: npm
    api_key: e15a99c8-cccb-480e-9d0e-3e73c837a748
    on:
        tags: true
