language: node_js
node_js:
  - 4.1
install:
  - npm install -g grunt-cli
  - npm install grunt
  # - npm install grunt-contrib-copy
  - npm install grunt-contrib-nodeunit
  # - npm install grunt-contrib-clean
  # - npm install grunt-contrib-uglify
  # - npm install grunt-contrib-jshint
  # - npm install grunt-contrib-concat
  # - npm install grunt-contrib-cssmin
  # - npm install grunt-contrib-less
  # - npm install grunt-react
  # - npm install grunt-replace

  - npm install jquery
  - npm install jsface
  - npm install moment
  - npm install jquery-deparam
  - npm install jquery-mousewheel
  - npm install react
  - npm install react-dom
  - npm install bootstrap-fileinput-npm
  - npm install bootstrap

#after_success:
#  - git config --global user.email "bradwoo8621@gmail.com"
#  - git config --global user.name "bradwoo8621"
#  - npm version patch

#notifications:
#  slack: nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ

notifications:
  slack:
    rooms:
      - nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ#travis-ci
#      - nest-parrot:z3jqw9krJbPu0CcQBKS90AnZ#random

deploy:
    skip_cleanup: true
    provider: npm
    email: bradwoo8621@gmail.com
    api_key: oHv3yA7k1CGCZrJmFsnfY3YCng+xVY0mXGciBGXg8rL2ZnxZzKLs+vSfQoz+vuHCOfS2o66tbqb2Jw6y4CtPml8u0p6BgPcDmZaWb8PmKXLaGYJvu8kIm3VkoMAo7T7taXsO8q042ZUI6Q88Tqrg3hGKptYzdascqU4t4vdo8xPYFOCWI3aBsFlS4DtyGzvibiE4YYR+Mj8VmOrAf7NPa7WJLRMOBcVPFPOlxS+1yzlHjXeXHDudWM24vlRMVkyF+b3cCdlkLWlDAwU9fAbZVb0o5LuUNSUVGvoV3lHVtA9VyA5SL2ayPkIwjJoQLejfrdf4pgdmZRrmwGnLWGfAqZb3ef5OKExABWhzM7f+QyEqC2lsLisXMxUmp1F/JOjQOVZ38oB6k84D2f4iQGY8Fh+NXf3yQ0UEQdAbNxIcHqNjcJOKpFSTT3RhIdFSPoJW7WFlwVjEKh2CbLbri8xtg/o2+csv9k2Z9cCHcUT+vByxx5VKSaxY22fSmqi9to0Fx/7avVvnl2ploPz6wMHKDQ4bX2hzRo2DBUEnfCh2Bzh8m1gt8OchqDkIxpaMW9Hp1ZAdbr5YXuRRg0DD9GkEvCIm/1wIAg/u3F+hkl4OPa//HwW7y9BjbEJqZZFeK7mULON6O4bEtT3bW6TsG8vogjPPLcVp7UbunYw0xX4msfw=
    on:
        tags: true
