language: node_js
node_js:
  - 0.12
install:
  - npm install -g grunt-cli
  - npm install grunt
  # - npm install grunt-contrib-clean
  # - npm install grunt-contrib-jshint
  - npm install grunt-contrib-nodeunit
  # - npm install grunt-contrib-uglify
  # - npm install grunt-react
  - npm install jquery
  - npm install jsface
  - npm install moment
  - npm install jquery.browser
  - npm install jquery-deparam
  - npm install jquery.mousewheel
  - npm install react
  - npm install bootstrap-fileinput
